module.exports = [
    {selector:'#first_name', value:'Test'},
    {selector:'#last_name', value:'Test'},
    {selector:'#organization', value:'Test'},
    {selector:'#Job_Title', value:'Test'},
    {selector:'#address', value:'Test'},
    {selector:'#city', value:'Test'},
    {selector:'#state', value:'Utah'},
    {selector:'#zip', value:'Test'},
    {selector:'#country', value:'United States'},
    {selector:'#phone', value:'Test'},
    {selector:'#email', value:'Test@test.test'},
    {selector:'#comment', value:'QA Automated test'},
    {selector:'#PO_Number', value:'123456789'},
    {selector:'#Howdid', value:'Friend or Coworker'},
]